### ISSUE TITLE
Unable to load nvme kernel module after applying the fix

### ISSUE THREAD

**Issue by lemourin** [m4ng0squ4sh/razer_blade_14_2016_acpi_fix#1]
Hi,
after applying the fix, my system says there is no root partition(in my case `/dev/nvme0n1p6`) and then it shows me the `(initramfs):` prompt. I'm using Ubuntu 16.10 with the systemd-boot bootloader; I also tried the fix on Arch Linux, but with the same result. 
I uploaded dmesg log from that failed startup, there are some lines I find interesting:
`[    0.235414] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM`
`[    2.715192] nvme nvme0: Removing after probe failure status: -19`
I was able to retrieve this log by plugging in a simple pendrive, `/dev/sdX` partitions seem to work.

Acpidumps and stuff: https://bugs.launchpad.net/lpbugreporter/+bug/752542/comments/797

**Edit**: I tried to use `ssdt5_orig.dsl` as the `ssdt5.dsl` file, 
I just changed `DefinitionBlock ("", "SSDT", 2, "SaSsdt", "SaSsdt ", 0x00003000)`
to `DefinitionBlock ("", "SSDT", 2, "SaSsdt", "SaSsdt ", 0x00003001)` and the issue still persists D:
So the conclusion is that our `ssdt5_orig.dsl` files should be different.

[dmesg.txt](https://github.com/m4ng0squ4sh/razer_blade_14_2016_acpi_fix/files/537431/dmesg.txt)

**Comment by r0l1** [comment]
Hmm. Ok let's compare our original SSDT tables. I added a [simple script](https://github.com/m4ng0squ4sh/razer_blade_14_2016_acpi_fix/blob/master/scripts/get_acpi_tables.sh) to extract and disassemble the ACPI tables. This will create a compressed archive. Please upload it. The generated SSDTs tabled will differ from the previous acpidumps...

EDIT:

The following can be ignored. This is just a warning and I get the same message.

```
[ 0.235414] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
```

**-19** in the other error is a Linux System error of type: `No such device`. I have to see the diffs of the SSDTs...

**Comment by lemourin** [comment]
[acpi_tables.tar.gz](https://github.com/m4ng0squ4sh/razer_blade_14_2016_acpi_fix/files/538186/acpi_tables.tar.gz)

**EDIT**: I got it working ;D
I found the diff between your `ssdt5_orig.dsl` and my `ssdt5.dsl`.
It was: 
`73c73`
`<     OperationRegion (SANV, SystemMemory, 0x3AE16D98, 0x013F)`
`---`
`>     OperationRegion (SANV, SystemMemory, 0x3AE5ED98, 0x013F)`

I fixed it accordingly in repository's `ssdt5.dsl` and now it works like a charm ;D
Now I have working touchpad AND bbswitch. Thanks!

**Comment by r0l1** [comment]
Great!
I changed the build process to use the ACPI tables of the local build machine. 00a5709e2a930a95c5ba23c65719208588ee3a61

Can you give it a try if this works now for you?

```
sudo make all
sudo make install
```

**Comment by lemourin** [comment]
Looks like your new scripts are working ;D
I guess the issue can be closed now.

**Comment by r0l1** [comment]
Perfect!
