### ISSUE TITLE
Getting this fix on Ubuntu/GRUB2

### ISSUE THREAD

**Issue by ghost** [m4ng0squ4sh/razer_blade_14_2016_acpi_fix#4]
Hello @m4ng0squ4sh I am trying to get this fix working on Ubuntu 16.10. My system is the one with the new GTX 1060. I guess not much has changed in this one from the early 2016 model.

I am stuck with GRUB as it does not load multiple initrd images. Is there a way to have this fix loaded in my current setup without changing the bootloader? I have attached the ACPI table from my system in case it helps.

[acpi_tables.tar.gz](https://github.com/m4ng0squ4sh/razer_blade_14_2016_acpi_fix/files/678235/acpi_tables.tar.gz)

Thanks.

**Comment by jramapuram** [comment]
@lungten : it does work. You have to do the following manual edit (be aware that this file will change when you run commands like grub-update, etc): 

```bash
menuentry 'Linux Mint 18.1 Cinnamon 64-bit' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-9d998c5a-db02-41d6-a39e-79fcccc91241' {
  recordfail
  load_video
  gfxmode $linux_gfx_mode
  insmod gzio
  if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
  insmod part_gpt
  insmod ext2
  if [ x$feature_platform_search_hint = xy ]; then
    search --no-floppy --fs-uuid --set=root  9d998c5a-db02-41d6-a39e-79fcccc91241
  else
    search --no-floppy --fs-uuid --set=root 9d998c5a-db02-41d6-a39e-79fcccc91241
  fi
  linux	/boot/vmlinuz-4.9.0-040900-generic root=UUID=9d998c5a-db02-41d6-a39e-79fcccc91241 ro  nouveau.blacklist=1 quiet button.lid_init_state=open quiet splash $vt_handoff
  initrd	/boot/razer_acpi_fix.img /boot/initrd.img-4.9.0-040900-generic
}
```

**Comment by ghost** [comment]
@jramapuram Looks like it is working. Didn't know I could configure initrd that way. Thanks mate.

**Comment by r0l1** [comment]
@jramapuram It's possible to make this persistent. Not sure about Debian based systems, but with Arch Linux there is a `/etc/default/grub` file.

**Comment by jramapuram** [comment]
@m4ng0squ4sh : Yea, same on debian systems. This is what generates /boot/grub.cfg.
Do you happen to know what parameter can be changes to append the `razer_acpi_fix.img` ?

I believe only systemd allows this currently.

**Comment by r0l1** [comment]
@jramapuram Could you try [this](https://wiki.archlinux.org/index.php/DSDT#Loading_at_runtime)? If this works for you, could you please share your experience? Would like to add some documentation to the README for Grub bootloaders. Thanks!

**Comment by jramapuram** [comment]
@m4ng0squ4sh : sorry for the delay. I tried this on Manjaro (since it utilizes grub for some reason) and it bricked me. Had to chroot to fix. The bootloader gets stuck like [this](https://www.dropbox.com/s/8d0e55apv8qi5gu/2017-04-03%2011.33.56.jpg?dl=0) . I wonder if you can do something like what the `intel-microcode` does? In either case, I don't think this issue is resolved persay.

I basically have to do this everytime there is a kernel update:

```bash
sudo sed -i 's/\/boot\/intel-ucode.img/\/boot\/razer_acpi_fix.img \/boot\/intel-ucode.img/g' /boot/grub/grub.cfg
```
